version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: on-failure:1
    environment:
      POSTGRES_USER: cpu
      POSTGRES_PASSWORD: <DB-PASSWORD>
      POSTGRES_DB: discord
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

  rasa-pantern:
    image: 6fcfd022b54f
    container_name: rasa-pantern
    # Setup command:
    # command: uv run -m db_handling.handler
    restart: on-failure:1
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USERNAME: cpu
      DB_PASSWORD: <DB-PASSWORD>
      DB_NAME: discord
      TOKEN: "<TOKEN>"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:

