version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: on-failure:1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

  rasa-pantern:
    image: rasa-pantern:latest
    container_name: rasa-pantern
    # Setup command:
    # command: uv run -m db_handling.handler
    restart: on-failure:1
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      TOKEN: ${DISCORD_BOT_TOKEN}
      WEBSITE_DB_URL: ${WEBSITE_DB_URL}
    networks:
      - backend

  janus:
    image: janus:latest
    container_name: janus
    restart: on-failure:1
    depends_on:
      - postgres
    environment:
      DSEK_CLIENT_ID: ${DSEK_CLIENT_ID}
      DSEK_CLIENT_SECRET: ${DSEK_CLIENT_SECRET}
      DSEK_REDIRECT_URI: ${DSEK_REDIRECT_URI}

      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}

      COOKIE_SECRET: ${COOKIE_SECRET}
      DATABASE_URL: "postgresql://cpu:rasa-pantern@postgres:5432/discord"
    ports:
      -  "3000:3000"
    networks:
      - backend



volumes:
  pgdata:

networks:
  backend:

